# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# ------------------------- Configuration -------------------------

# Max targeting distance.
targetingRange: 40

# Targeting cursole width.
targetingWidth: 2.5

# Max targeting numbers.
maxTargetNum: 5

# Missile acceleration speed.
missileAccelSpeed: 0.4

# Missile maximum speed.
missileMaxSpeed: 2.0

# Explosion power.
explosionPower: 3

# Explosion damage amount.
explosionDamage: 3.0

# Material of launcher. Default is 'GOLD_HOE'
launcherMaterial: 'GOLD_HOE'

# Missile launcher item display name.
launcherDisplayName: '&9&lStinger'

# Infinite Missile Mode.
# If false, an ender pearl will be consumed by launching each missiles.
infiniteMissileMode: true

# If true, launcher can target to MOBs.
targetingToMob: true

# If true, launcher can target to other players.
targetingToPlayer: true

# If true, launcher can target to vechicles (minecart and boat).
targetingToVehicle: true

# If true, launcher can target to ender crystal.
targetingToEnderCrystal: true

# Material of consumed item per launching missile. Default is 'ENDER_PEARL'
consumeMissileMaterial: 'ENDER_PEARL'

# You can set the delay cycles it takes a while to run the lock-on,
#   when you hold clicking on the target.
# 1 cycle is 5 ticks.
# For example, if you set "lockonDelayCycle: 4",
#   the target is locked on to one seconds after the cursor by clicking.
lockonDelayCycle: 0

# ------------------------- Messages -------------------------

messageTargetCandidate: '&7target candidate: %name,  distance: %distance'
messageTargetted: '&6targeted %name. (%num/%max)'
messageEmptyMissile: '&cYou don''t have missile(%material) !'

# The following messages for Bukkit 1.8 or later.
messageWarning: '&c&n<<WARNING>>'
messageWarningMissileInbound: '&c&n<<WARNING MISSILE INBOUND>>'

# ------------------------- Sound -------------------------

soundLockonDelay: 'NOTE_PLING-0.5-1'
soundLockonTarget: 'ORB_PICKUP-1-1'
soundNoneTarget: 'IRONGOLEM_THROW-1-1.5'
soundLaunching: 'NOTE_BASS_DRUM-1-1,SILVERFISH_HIT-0.5-0,CHEST_CLOSE-1-1.8'
soundWarning: 'NOTE_PLING-1-0.5,ZOMBIE_UNFECT-0.7-2'
soundWarningMissileInbound: 'NOTE_PLING-1-0.5,ZOMBIE_UNFECT-0.7-2'
