name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.stinger.StingerMissile
author: ucchy
description: Stinger missile plugin for ${release.lang}
softdepend: [ColorTeaming]

commands:
  stinger:
    description: The command for StingerMissile.
    aliases: sm
    usage: |
           /<command> get - get new stinger missile.
           /<command> give (player) - give new stinger missile.
           /<command> reload - reload configuration file.
    permission: stinger.command
    permission-message: You don't have "<permission>" permission.

permissions:
  stinger.command:
    description: StingerMissile command permission.
    default: true
  stinger.reload:
    description: StingerMissile reload command permission.
    default: op
  stinger.get:
    description: StingerMissile get command permission.
    default: op
  stinger.give:
    description: StingerMissile give command permission.
    default: op
  stinger.action:
    description: StingerMissile action permission.
    default: true
  stinger.*:
    children:
      stinger.command: true
      stinger.reload: true
      stinger.get: true
      stinger.give: true
      stinger.action: true
    description: All of StingerMissile permission.
